### ISSUE TITLE
plot with rlnorm iterations is off for fbar?

### ISSUE THREAD

**Issue by rverkempynck** [flr/doc#10]
Hi at: http://www.flr-project.org/doc/ggplotFL_plotting_FLR_objects_with_ggplot2.html
there is a plot generated by:

fqs <- FLQuants(F = rlnorm(200, fbar(ple4), 0.15), SSB = ssb(ple4), Rec = rec(ple4), Catch = catch(ple4))
plot(fqs) + facet_wrap(~qname, scales="free")

The final year F plot is near 1.5, but when I check fbar(ple4) that F is at 0.38. Shouldnt the plotted F be near the fbar?

**Comment by iagomosqueira** [comment]
Yes, rlnorm takes the mean and sd in log scale, for example



fqs &lt;- FLQuants(F = rlnorm(200, log(fbar(ple4)), 0.15), SSB = ssb(ple4), Rec = rec(ple4), Catch = catch(ple4))



plot(fqs) + facet_wrap(~qname, scales="free")



lognormal is used there to avoid negative values





Iago



---- On Wed, 25 Apr 2018 15:34:32 +0200 rverkempynck &lt;notifications@github.com&gt; wrote ----




Ok, the rlnorm is the LOG normal distribution. Use rnorm and then it is the same.

Maybe for comparison reasons rnorm would be better in the tutorial, too?
