### ISSUE TITLE
multiple of replacement length error

### ISSUE THREAD

**Issue by rverkempynck** [flr/doc#11]
Hi, 

On the FLash Medium Term Forecast tutorial I keep having an error at:

    sample_years <- sample(dimnames(residuals(ple4_sr))$year, niters * 10, replace = TRUE)
and

    multi_rec_residuals[] <- exp(residuals(ple4_sr)[,sample_years])

error is:

    Error in do.call("[<-", c(list(x = y), iper, list(value = aperm(unname(value),  : 
      number of items to replace is not a multiple of replacement length

However, the error is not there when I do **not** multiply niters by 10 when defining sample_years. Why are we multiplying this by 10? Is that for the ages? It doesn't work anyway.
Regards, 
Ruben

**Comment by iagomosqueira** [comment]
The 10 there refers to the number of years, not ages. So number of samples is niter * nyears

I have just tested it, including installation of packages from the repository and it works for me.

What OS are you using? Versions of R and FLCore?

**Comment by rverkempynck** [comment]
Hi Iago, thanks for your help. If it refers to years than it also works on my machine. I was doing a 50 year forecast. By changing the 10 in nyears the code works.

Thanks again,

Regards,
Ruben
