### ISSUE TITLE
FLBEIA tutorials html links broken

### ISSUE THREAD

**Issue by marchtaylor** [flr/doc#21]
Hi there,
It appears that the html links to only 2/6 FLBEIA tutorials are currently available:

- Conditioning FLBEIA using Smart Conditioning Functions
- A simple example on how to use FLBEIA [**working**]
- A simple example with multiple dimensions in FLBEIA [**working**]
- Using Stock Assessment models in the Management procedure of FLBEIA
- Testing different Management Strategies in FLBEIA
- Data Limited MSE in FLBEIA

Maybe a problem with the build?

**Comment by iagomosqueira** [comment]
Links corrected now, the tutorial files had their name changed at some point. flr.github.io@f97e876
