### ISSUE TITLE
XSA with missing years

### ISSUE THREAD

**Issue by karlmichaelwerner** [flr/doc#26]
Dear developers of FLR,

firstly, thanks a lot for providing this important tool.
I have a question regarding missing years in the catch-at-age time series for doing an XSA.
We are now trying to set up an XSA for redfish (Sebastes mentella) and have biomass/abundance survey indices and catch-at-age data for ~40 years. However, for 3 years, catch-at-age is missing because we do not have any information regarding length/age distribution of the commercial catches. The survey index does, however, exist for these years.
Can we still compute the XSA with these 3 missing years?

Best regards from the Thünen Institute
Karl

**Comment by iagomosqueira** [comment]
Also a few short examples by typing `?sca`

**Comment by karlmichaelwerner** [comment]
Hi Iago,

I have never thanked for your support, this was helpful.
As this is a first attempt to do a stock assessment on this stock, we liked to start with an XSA and then build on this with more sophisticated models later. I think it is nice if the results of the different approaches can then be compared.

Take care and I hope you have nice christmas days
Karl
